travis:
  secure:
    BINSTAR_TOKEN: mGQPpwdKHgLqWeruivc5HD5kwl30LG3oHcOlJ+cq+ZwpKBVyg9vFGRwTp9Al3iuOFs+TS5kHqKmRZLWufFUCh2f1wWWHaEktuB19UHJqoBWfXEl3abuHZ5oad/URL+lfB0EblZp1JvmEDcNPq2Uh+VsG4wAIg7oT57GnaldXKY6NpPM8r8fEvf4lmXKn4BuFSA+zkLIYxYW84hxtcoEg0KCUSMdHaxLO/FnDlpTMCxZToBuwIDuvfyWwlqFvEk6n7VgXfBbGx28jonJOLUxr/NsLL2nmXi94ZIV43uKy5qISt0f6MoZNjQ6whBECfBe8ZuXeBSF3HKQU14UqSrXnshMIkKypa7+Gp9bmpByThS6pW/1V7XFPfpvv9eUPoN5gjOVlsYGKHNhUXS5Pp2M150tbljqga90DVCNEsjq2mxsjUXBm3BGiUySoLsW0GqM+Bc/5yTgyOwRqO3MU7qH9CzXLt4ROROBi/ZU4xdqkcxP/Fv/oI0serG7kWFuvn7nupLtqzvu9FibsLD1GB2sKp4PRmuXuoPyRYEo8hQS/1d2IRfRuF0j5cUCYj7EuJmIGwFwcCtT0Wy+11INvbptXqVtD0s/j738HPm3E8tkUjeXaGHa8aPdiqbIZtAmmpcjs+PUsyiX8oiV4yH+H7/Yd8Kjo01UVEE/kqiQeVA5M5eA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
