travis:
  secure:
    BINSTAR_TOKEN: DZHgIGIySK76kS0quaJCsMRbwiSD07/jad+PBBezuInmVMtaQxnZy7uu5cRwuT3NSXG1N5HjWOO4z7Tqw0ebhwmxHz4Mjk7W+/Ct1kTozX+fBcffukMDeaQlC+L3EewufilA3N1OuRGk/Y7DlIjzG2xlM8taWK9jjFTvD5llPoaLb0Mz03oZRZS7bcdSgsiD4rRz2mNHpcrBjRODuliISnDru9/hwpaeL6M6Hf/1XW8YgFjWk87AnvwE01i7sXpFePkv4O3v3ccge5fBOyj6zd4sCShq/oWHdNnY8jxpdrXxIxw4zTyW0xdgTr87kvVi2HxL4FTO/QcEiBNkXY4Aupozzr01YtXuQYzTwQsFT8yHKsoCOfxsEerfWsMirQ1mhLzxvRS/w0mmVtKe24K+aaN7YegIQ/DX1jhwYwnwpiJepxpmUk5pgMP13hY5/zfBLgpKtLj3lr6BbJiyEak6J/oPdNGU0aWG7KvHh94DB9ZF1+1GuRTYnYUddOu0gNA0mO59EWFbKFm70mNyOVOaVLHgQ2TBR3VYDm5FnVDWYfvmGBUw+R2ab0m91tniGgY466H4dUEpJ/Pm7iGJVPbL+Mdg1i/NyWLatimfOX3Nc0DaiSTzsdVFQFW+5nvY1N8RbViOYvLzPwiVmauL7x0ZCueZayAVqD/I5dFCoNFoLiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
